### ISSUE TITLE
i get an issue after inserting the token

### ISSUE THREAD

**Issue by laboratory99992** [DarkGuy10/Nukecord#2]
issue looks as such [screenshot](https://prnt.sc/26ptkm6)

**Comment by DarkGuy10** [comment]
@quantinium16  It works perfectly fine for me
![image](https://user-images.githubusercontent.com/62807269/155965265-1d42d0fb-9150-443a-a8a7-984190bce5ab.png)
Make sure you copy the token properly, note that changing your account password resets your token.
To use a fresh token, delete the `token` key from `config.json`
