### ISSUE TITLE
no module named 'discord'

### ISSUE THREAD

**Issue by theunknownvoid** [DarkGuy10/Nukecord#4]
when i run 'python N-u-ked.py' this happens
im pretty new to self bots and coding itself so excuse me if im being dumb
![image](https://user-images.githubusercontent.com/104006961/167689306-6cdad3f2-2cd7-4b97-be22-000da235c7fb.png)

**Comment by DarkGuy10** [comment]
> when i run 'python N-u-ked.py' this happens im pretty new to self bots and coding itself so excuse me if im being dumb ![image](https://user-images.githubusercontent.com/104006961/167689306-6cdad3f2-2cd7-4b97-be22-000da235c7fb.png)

You'll have to install discord.py (as it says in the README)
```
py -3 -m pip install -U discord.py
```
On windows, open cmd and run this first ^
